[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
basic_storage = "FmF6PxiE8RM5xgFvuRoDc9t5SxXPR6uzpEky984NJPYx"
mapping_storage = "5GqZxN1zoSURmJZPwfigvEKEVexJhNnya4JQmBam96pv"
nested_storage = "HivorQTcSP2YGdPSpfzZZEB8nxamkgxFgHMjBqk8ttfT"
simple_token = "49Y21ERXmx4XwtVNoKDF97z83t9CcEPgX7ePDJPJDbbd"
sol_bank = "2TtfrjoAQiDGqXqSSb4K8g9dc6u2t6NhjFsoSKaEU4Z8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
